apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    app: springapp
specs:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
    spec:
      containers:
        - name: springapp
          image: mamusagil/devops-main:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30100