apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  labels:
    app: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  strategy: {}
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - image: mamusagil/devops-main:latest
        imagePullPolicy: Always
        name: springapp
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30100