apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdemo
  labels:
    app: kubernetesdemo
specs:
  containers:
  - name: app-container1
  image: eu.gcr.io/darwin-imagepull-project/app-container1
  imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: kubernetesdemo
    spec:
      containers:
        - name: kubernetesdemo
          image: yolanv/kubernetesdemo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemo
spec:
  type: NodePort
  selector:
    app: kubernetesdemo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30011